### ISSUE TITLE
anime.disappointyour.mom

### ISSUE THREAD

**Issue by nightpool** [thejamesm/whereiswaypoint#6]
http://anime.disappointyour.mom/

**Comment by thejamesm** [comment]
👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍

**Comment by thejamesm** [comment]
I put it on the list for "social", since it directs to a tweet. The Twitter bot and whereiswaypoint.info draw from a concatenation of all the lists, so it should show up around and about.
